name: Deploy site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: OpenAEC-Foundation/github/.github/workflows/deploy-site.yml@main
    with:
      deploy_host: ${{ vars.DEPLOY_HOST }}
      deploy_port: ${{ vars.DEPLOY_PORT }}
      deploy_user: ${{ vars.DEPLOY_USER }}
      deploy_path: ${{ vars.DEPLOY_PATH }}
      deploy_source: ${{ vars.DEPLOY_SOURCE }}
      node_version: ${{ vars.NODE_VERSION }}
      setup_command: ${{ vars.SETUP_COMMAND }}
      install_command: ${{ vars.INSTALL_COMMAND }}
      build_command: ${{ vars.BUILD_COMMAND }}
    secrets:
      deploy_ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
